---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-token
  namespace: forgejo-runner
spec:
  encryptedData:
    token: AgDZxMdMYcKtM8TPsCcvRjIICZCics9MgUCPVmMeAGL2qZ3sYmi99nIa6Eeuk6hzn62TfVYwidjAymGPz+3QgiC43LL/jHBHLJY+fR1Tiy/DxNsruchUADR2uSLI4fPYthWlrOeQCXqZUdNGzQLLiCVQaQ3WGByA+Jtih0gRsQ0kCJs60JS1Xikc9AErz5iYe6ZZISMs1Jk8kkYWtI+dfB0Lqbm4OJ9ObviIYnKgrNcXRfjPwMtYsdScnyRXypFHGSt3vOZQFtd5DHCuJmmBU6r71QQsk34aveLo2unYhTAOwuImnO5tkA3tMbHCd9k+Idc1CJehYqY89aSj6mEY5yKK2wz7byYDHAbDtrAmYJuIiSjobxqpup84phwvW7dZsbWZdte9botn+QnfAdDD3pTgWMPx6AioRF+02X0Dzygta+vStZjMX4QxtPMa56lvNEFrBYXADnO8lTdUr74DgkB7GmQRUgS+ioz7frM4ulZhO85bHU+RiKcXTKCmyvWoIqTPdrsoNxfjSscVWh2oqDeLOUGsJDo3SHi/fgObMqecTJw7OLkUqoG4glufpZVQSVHSk3nHFpDibizigpcQeUZnljJJYycsuBWjvazOLxnmL4vPErIokMPpm66EZvFkjkQhxAam5j/Tv/DB2Foeh4gBjkEXcXwBav+WwcO8+rwbf5JIS6BIuj5j05EMYVK9TH+ObNY5f9dV7/XsU1PbZGrz78B4g/GuLEGqwFPYs+GLYpV2d3YPC8AS
  template:
    metadata:
      name: forgejo-runner-token
      namespace: forgejo-runner
