apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/david-bachelor-project/backend.git
    targetRevision: HEAD
    path: src/main/setup/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
