apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb-csi
  namespace: argocd-apps
spec:
  project: default
  source:
    repoURL: https://github.com/DavidJohannesS/argocd-bootstrap.git
    targetRevision: HEAD
    path: infra/smb-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
