apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ums-media
  namespace: ums
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  volumeName: ums-media-pv
  storageClassName: ""
