apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

helmCharts:
  - name: forgejo
    releaseName: forgejo
    namespace: forgejo
    version: 16.2.1
    repo: oci://code.forgejo.org/forgejo-helm
    valuesFile: values.yaml
