apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:latest
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp=1
            - --memory=1G
            - --reserve-memory=0M
            - --node-id=0
            - --check=false
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr=PLAINTEXT://redpanda.kafka.svc.cluster.local:9092
            - --set
            - redpanda.enable_transactions=false
            - --set
            - redpanda.enable_idempotence=false
          ports:
            - containerPort: 9092
