apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

resources:
  - namespace.yaml

helmCharts:
  - name: vikunja
    releaseName: vikunja
    namespace: vikunja
    repo: oci://ghcr.io/go-vikunja/helm-chart
    version: v2.0.2
    valuesFile: values.yaml
    includeCRDs: true
