apiVersion: v1
kind: Namespace
metadata:
  name: redpanda-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-operator
  namespace: redpanda-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-operator
  template:
    metadata:
      labels:
        app: redpanda-operator
    spec:
      serviceAccountName: redpanda-operator
      containers:
        - name: operator
          image: docker.redpanda.com/redpandadata/redpanda-operator:latest
